modLoader = "javafml"
loaderVersion="[41,)"
issueTrackerURL = "https://github.com/InnovativeOnlineIndustries/MatterOverdrive/issues"
license = "MIT"
[[mods]]
modId = "matteroverdrive"
version = "${file.jarVersion}"
displayName = "Matter Overdrive"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/matter-overdrive"
authors = "Buuz135, Sekwah41, Lanse505"
logoFile = "mo_logo.png"
description = '''
"Tinky Winky says 'No'" - Lanse505
'''

[[dependencies.matteroverdrive]]
modId = "forge"
mandatory = true
versionRange="[41.0.94,)"
ordering = "NONE"
side = "BOTH"

# https://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
[[dependencies.matteroverdrive]]
modId = "minecraft"
mandatory = true
versionRange="[1.19]"
ordering = "NONE"
side = "BOTH"
